const PROJECTS_DATA = [
  {
    id: 1,
    linkUrl: "jotrackercovid19",
    title: "jotrackercovid19",
    desc: "It's a tool to follow the evolution of the Coronavirus epidemic in the world.",
    technos: ["React", "Chart JS", "API"],
    imageProject: "/assets/jotrackercovid19_2.jpg",
  },
  {
    id: 2,
    linkUrl: "latest-movies",
    title: "Latest Movies",
    desc: "A project that shows the latest films that have been released.",
    technos: ["React", "Material-ui", "API"],
    imageProject: "/assets/latest-movies.png",
  },
  {
    id: 3,
    linkUrl: "jolesbonspronos",
    title: "Jolesbonspronos",
    desc: "A project that offers sports betting to customers.",
    technos: ["React", "MongoDB", "Graphql"],
    imageProject: "/assets/jolesbonspronos.jpg",
  },
  {
    id: 4,
    linkUrl: "Msj-Maconnerie",
    title: "MSJ Maçonnerie",
    desc: "I used an existing WordPress theme.",
    technos: ["Wordpress", "Css", "Html"],
    imageProject: "/assets/msj-maconnerie.jpg",
  },
  {
    id: 5,
    linkUrl: "john-sports",
    title: "John sports",
    desc: "I built this project with Gatsby.",
    technos: ["Gatsby", "Snipcart"],
    imageProject: "/assets/john-sports-1.jpg",
  },
  {
    id: 6,
    linkUrl: "campus",
    title: "Camp'us",
    desc: "A simple project for mobile.",
    technos: ["Gatsby", "React Native", "Laravel"],
    imageProject: "/assets/campus-1.jpg",
  },
  {
    id: 7,
    linkUrl: "Reparizy",
    title: "Reparizy",
    desc: "This site connects mechanics and users.",
    technos: ["Symfony", "Materialize", "Javascript"],
    imageProject: "/assets/reparizy-1.jpg",
  },
]
export default PROJECTS_DATA
