backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

# Uncomment local_backend when you need to develop in your local
local_backend: true # run npx netlify-cms-proxy-server for local testing

media_folder: "static/assets" 
public_folder: "/assets" 

collections:
  - name: 'posts' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Posts' # Used in the UI
    label_singular: 'Post' # Used in the UI, ie: "New Post"
    description: >
      Create awesome content here.
    folder: 'src/content/posts'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    summary: '{{title}} — {{year}}/{{month}}/{{day}}'
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: 'Template', name: 'template', widget: 'hidden', default: 'project-post'}
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - { label: 'Slug', name: 'slug', widget: 'string', hint: 'Start slug with /. Use only alphanumeric characters, - and _. Avoid spaces in any cases.'}
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          dateFormat: 'YYYY-MM-DD',
          timeFormat: 'HH:mm',
          format: 'YYYY-MM-DD HH:mm',
        }
      - { label: 'SEO Description', name: 'description', widget: 'text' }
      - {
          label: 'Featured Image',
          name: 'featuredImage',
          widget: 'image',
          required: false,
          tagname: ''
        }

      - { label: 'Body', name: 'body', widget: 'markdown', hint: 'Main content goes here.' }
      - label: Social Icons
        name: socialIcons     
        file: "src/constant/technos.json"
        fields:
          - label: Social Icons
            name: socialIcons  
            widget: list
            collapsed: true
            hint: "Here you can add social icons, Click on 'Add social icons'"  
            fields:
              - label: "Icons"
                name: "icon"
                widget: "select"
                options: ["facebook", "twitter", "linkedin", "youtube", "instagram", "rss", "github", "telegram", "pinterest", "snapchat", "skype", "wordpress", "dribbble", "medium", "behance", "vk"]
                hint: "Select the Icon"   
              - widget: string
                name: url
                label: url
                required: true
                hint: "Paste the 'URL' of your Social media" 
            
